# Generated by Django 4.1.3 on 2024-01-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('fee', models.IntegerField()),
                ('startdate', models.DateField()),
                ('timings', models.TimeField()),
                ('trainer_name', models.CharField(max_length=50)),
                ('trainer_exp', models.CharField(max_length=50)),
                ('training_mode', models.CharField(max_length=50)),
            ],
        ),
    ]
