# Generated by Django 4.1.3 on 2024-01-07 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0002_contactdata_commentdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentdata',
            old_name='contnet',
            new_name='comment',
        ),
    ]
