# Generated by Django 4.1.3 on 2024-01-07 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0003_rename_contnet_commentdata_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentdata',
            old_name='comment',
            new_name='content',
        ),
    ]
